<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250731211023 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo VARCHAR(255) NOT NULL, leite DOUBLE PRECISION NOT NULL, racao DOUBLE PRECISION NOT NULL, peso DOUBLE PRECISION NOT NULL, nascimento DATE NOT NULL, status VARCHAR(255) NOT NULL, fazenda_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_99D43F9C20332D99 ON cow (codigo)');
        $this->addSql('CREATE INDEX IDX_99D43F9CD4A3545F ON cow (fazenda_id)');
        $this->addSql('CREATE TABLE farm (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, tamanho DOUBLE PRECISION NOT NULL, responsavel VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5816D04554BD530C ON farm (nome)');
        $this->addSql('CREATE TABLE farm_veterinarian (farm_id INT NOT NULL, veterinarian_id INT NOT NULL, PRIMARY KEY (farm_id, veterinarian_id))');
        $this->addSql('CREATE INDEX IDX_499A5CC65FCFA0D ON farm_veterinarian (farm_id)');
        $this->addSql('CREATE INDEX IDX_499A5CC804C8213 ON farm_veterinarian (veterinarian_id)');
        $this->addSql('CREATE TABLE veterinarian (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, crmv VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E5C18053697FA2C ON veterinarian (crmv)');
        $this->addSql('ALTER TABLE cow ADD CONSTRAINT FK_99D43F9CD4A3545F FOREIGN KEY (fazenda_id) REFERENCES farm (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE farm_veterinarian ADD CONSTRAINT FK_499A5CC65FCFA0D FOREIGN KEY (farm_id) REFERENCES farm (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE farm_veterinarian ADD CONSTRAINT FK_499A5CC804C8213 FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cow DROP CONSTRAINT FK_99D43F9CD4A3545F');
        $this->addSql('ALTER TABLE farm_veterinarian DROP CONSTRAINT FK_499A5CC65FCFA0D');
        $this->addSql('ALTER TABLE farm_veterinarian DROP CONSTRAINT FK_499A5CC804C8213');
        $this->addSql('DROP TABLE cow');
        $this->addSql('DROP TABLE farm');
        $this->addSql('DROP TABLE farm_veterinarian');
        $this->addSql('DROP TABLE veterinarian');
    }
}
